updated

diff --git a/.github/workflows/publish-release.yml b/.github/workflows/publish-release.yml
--- a/.github/workflows/publish-release.yml
+++ b/.github/workflows/publish-release.yml
@@ -391,6 +391,32 @@ jobs:
         shell: bash
         run: |
           make start-e2e-import-mainnet-test
+          container_id=$(docker ps --filter "ancestor=orchestrator:latest" --format "{{.ID}}")
+          if [ -z "$container_id" ]; then
+              echo "Orchestrator container is not currently running. Exiting..."
+              exit 1
+          fi
+          echo "Monitoring Orchestrator container with ID: $container_id"
+          while true; do
+              current_status=$(docker ps -q | grep $container_id || echo "docker-ps-error")
+              if [ "$current_status" == "docker-ps-error" ]; then
+                  echo "***********************************"
+                  echo "*                                 *"
+                  echo "*                                 *"
+                  echo "*        TESTING COMPLETE         *"
+                  echo "*                                 *"
+                  echo "*                                 *"
+                  echo "***********************************"
+                  docker logs $container_id || echo "no logs"
+                  exit 0
+              else
+                  echo "Testing in progress still...."
+                  if [ "${{ github.event.inputs.debug }}" == "true" ]; then
+                    docker logs $container_id || echo "no logs"
+                  fi
+              fi
+              sleep 5
+          done
 
       - name: Mark Job Complete Skipped
         if: ${{ github.event.inputs.skip_checks == 'true' }}
